services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ['7860:7860']
    env_file: .env
    environment:
      GEMINI_API_KEYS: |
        skkkey1,skkkey2,
        skkkey3,skkkey4
